name: Model Conversion Request
description: Convert Java model to Bedrock format
title: "[Model] Convert: "
labels: ["model-conversion"]
body:
  - type: markdown
    attributes:
      value: |
        ## Java to Bedrock Model Converter
        
        Provide the URL to your Java model JSON file and a name for the model.
        The converter will automatically process it and provide the Bedrock format output.
  
  - type: input
    id: model-url
    attributes:
      label: Model URL
      description: Direct download URL to the Java model JSON file
      placeholder: https://example.com/models/my_model.json
    validations:
      required: true
  
  - type: input
    id: model-name
    attributes:
      label: Model Name
      description: Name for the model (used in geometry identifier)
      placeholder: campfire, custom_item, etc.
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context or requirements
      placeholder: Special rotation requirements, texture size, etc.
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have provided a valid direct download URL to a Java model JSON file
          required: true
        - label: The model follows standard Java Edition model format
          required: true
